### ISSUE TITLE
Minimum required xUnit.net version (in .nuspec file)

### ISSUE THREAD

**Issue by moodmosaic** [GreanTech/Exude#12]
I am about to use Exude in a project named [Idioms.FsCheck](https://github.com/AutoFixture/AutoFixture/issues/198#issuecomment-37343032) which uses xUnit 1.8.0.1549.

Exude is not published on NuGet Gallery (yet) so I setup a local package source to install it.

However, _Grean.Exude.nuspec_ file doesn't currently include a dependency element (as described [here](http://docs.nuget.org/docs/reference/nuspec-reference)) to also pull and install xUnit.

---

On my machine all tests passed with xUnit 1.8.0.1549, so I was wondering if it makes sense to require >= xUnit 1.8.0.1549 in the .nuspec as the lowest common denominator.

**Comment by ploeh** [comment]
Exude is build against [xUnit.net 1.9.2](http://www.nuget.org/packages/xunit/1.9.2), which may be a mistake on my part. Should we consider downgrading it to xUnit 1.8.0.1549? Or could Idioms.FsCheck be built on xUnit 1.9.2 instead?

When we publish Exude on NuGet.org, obviously it should have a correct dependency on xUnit.net, so thank you for pointing out that omission.

**Comment by moodmosaic** [comment]
Idioms.FsCheck could be built on xUnit 1.9.2 but that would mean two different xUnit versions throughout the AutoFixture codebase because AutoFixture.Xunit can't be just upgraded without a breaking change.

Currently [I use Exude from Idioms.FsCheck](https://github.com/moodmosaic/AutoFixture/blob/idioms-fscheck/Src/Idioms.FsCheckUnitTest/ReturnValueMustNotBeNullAssertionTest.fs#L47-L130) with a (manually written) assembly binding redirect:

```
<dependentAssembly>
  <assemblyIdentity name="xunit" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-1.9.2.1705" newVersion="1.8.0.1549" />
</dependentAssembly>
```

Since Exude tests passed with xUnit 1.8.0.1549 and Idioms.FsCheck (which uses xUnit 1.8.0.1549) also works I think it would be OK to downgrade to xUnit 1.8.0.1549.

If you agree on the downgrade I would happily send a Pull Request.

**Comment by ploeh** [comment]
Is the _motivation_ for making the downgrade appropriate?

One thing is that AutoFixture.Xunit and most AutoFixture unit tests currently depend on xUnit.net 1.8.0.1549, but we're not building Exude particularly for AutoFixture. Someone else might come along and want to use Exude together with _their_ code base, and it uses some other version of xUnit.net.

Now, when we look at Postel's law, I think it makes sense to make as tolerant requirements as possible, so if we can build Exude on an older version of xUnit.net, we should consider doing that.

However, which version should we pick? It's important to be sure that if we pick an old release, and other clients want to upgrade, there should be no breaking changes. What versioning scheme does xUnit.net use?

When you look at the xUnit.net release list, it looks like they switched to Semantic Versioning at version 1.9.1...

**Comment by moodmosaic** [comment]
The motivation ends up being the Postel's law and the fact that xUnit 1.8.0.1549 seems stable.

I am quite confident on that because not so long ago [we had to upgrade from xUnit 1.6.1](https://github.com/AutoFixture/AutoFixture/issues/56#issuecomment-22776045) and I found several issues with various newer versions [including 1.9.1](https://twitter.com/nikosbaxevanis/status/369040995041554432).

OTOH the [most downloaded](http://www.nuget.org/packages/xunit) version on NuGet is 1.9.2. So, at the end the value of the dependency element in the _.nuspec_ file might be more important than the compiled version...

**Comment by ploeh** [comment]
I admit that with AutoFixture, we've been compiling against _old_ versions of xUnit.net for a _long_ time, but that I've personally always used a newer version for my own testing, and that has rarely caused me any problems. So empirically, we know that xUnit.net is quite stable, and it's probably quite safe to use an older version.

However, when you intend to use it with F#, as do we, there's actually [a minor bug related to F#](https://xunit.codeplex.com/workitem/9868) that wasn't [fixed until xUnit.net 1.9.2](https://xunit.codeplex.com/SourceControl/list/changesets). Personally, I don't care about that bug any longer, because I use Unquote instead of xUnit.net's own assertions... Actually, I can't really figure out if this has any impact at all on the discussion... :$

**Comment by moodmosaic** [comment]
Perhaps xUnit version could remain as-is (1.9.2) and only require xUnit >= 1.8.0.1549 in the _.nuspec_ file...

**Comment by ploeh** [comment]
Wouldn't that be making a promise that we have no idea if we can keep?

**Comment by moodmosaic** [comment]
Well, unless the _exact_ version is specified in _.nuspec_ file, it's out of control (kind of). That's because of two reasons that I can currently think:
- Multiple sets of version ranges are [not allowed](http://stackoverflow.com/questions/21941850/is-it-possible-to-use-multiple-sets-of-version-ranges-in-nuget-nuspec-files) on NuGet
- There is no guarantee that clients won't break with future releases of a dependency (a good example can be found [here](https://github.com/AutoFixture/AutoFixture/issues/240#issuecomment-33912071))

**Comment by ploeh** [comment]
What I meant was: if we only require xUnit >= 1.8.0.1549, but build on 1.9.2, then how do we know that it actually works on 1.8.0.1549... or 1.9.1?

**Comment by moodmosaic** [comment]
We don't know it automatically (as part of the build automation process) - only empirically. The hypothesis is quite similar also for **>** 1.9.2 although less risky. (That is, the guarantee is only for the **=** version).

**Comment by ploeh** [comment]
In the case where we state that the requirement is xUnit.net >= 1.9.2, I would consider it the responsibility of xUnit.net if they break compatibility.

**Comment by moodmosaic** [comment]
So it looks like requiring >= 1.9.2 is safer and involves less (potential) backwards compatibility issues.

**Comment by ploeh** [comment]
I didn't say that, but I _do_ think that the requirement we put in the .nuspec file should reflect the version Exude is built against.

**Comment by moodmosaic** [comment]
Yes, indeed. And if necessary, a client may use an assembly binding redirect for older xUnit versions (as in [this](https://github.com/GreanTech/Exude/issues/12#issuecomment-37405476) case which works good).

**Comment by ploeh** [comment]
I lost track now. What do you suggest?

**Comment by moodmosaic** [comment]
Based on all the above comments my suggestion would be to simply require _xUnit >= 1.9.2_ in _.nuspec_.

---
- 1.9.2 is the [most downloaded](http://www.nuget.org/packages/xunit) version on NuGet.
- Clients using 1.8.0.1549 [can use an assembly binding redirect](https://github.com/GreanTech/Exude/issues/12#issuecomment-37405476).
- Clients using the [buggy 1.9.1](https://twitter.com/nikosbaxevanis/status/369040995041554432) can either use an assembly binding redirect or upgrade.

**Comment by ploeh** [comment]
OK, then we just need to add the requirement to the .nuspec file.

**Comment by ploeh** [comment]
Resolved in ff3d069ba9a8d5f9c44d8b725aed939d541d53c8

**Comment by CumpsD** [comment]
Guessing this can be re-opened, if Grean could support xUnit 2.0.0? :)

**Comment by ploeh** [comment]
@CumpsD, I created [a new issue instead](https://github.com/GreanTech/Exude/issues/21).
