### ISSUE TITLE
TestCase adapting Action

### ISSUE THREAD

**Issue by ploeh** [GreanTech/Exude#16]
The `TestCase` class currently adapts an `Action<object>`. The `object` supplied to the delegate is an instance of the test class that contains the test method adorned with the `[FirstClassTests]` attribute.

However, in some cases, the test writer may not care about this instance, so it would be appropriate that he or she could also supply an `Action`:

``` C#
yield return new TestCase(() => Assert.Equal(1, 1));
```

When that's the case, perhaps `TestCase.ConvertToTestCommand` should return an `ITestCommand` instance (which could still be `FirstClassCommand`) with `ShouldCreateInstance` returning `false` instead of `true`.

**Comment by moodmosaic** [comment]
The `TestCase` class also exposes an inspection property named _TestAction_ of type `Action<object>`.

Since there is no type hierarchy between `Action` and `Action<T>` what will be the purpose of that property?

**Comment by ploeh** [comment]
One option is to adapt the `Action` to an `Action<object>` by chaining the constructors.

Another option is to create a new class instead of `TestCase`.

**Comment by moodmosaic** [comment]
The first option, with the constructor chaining, sounds good.

In general I would lean towards creating a new class but in this particular case the constructor chaining helps keeping a [low surface-to-volume ratio](http://www.laputan.org/selfish/selfish.html#LowSurfaceToVolumeRatio), I think.

**Comment by moodmosaic** [comment]
Oh, it looks like the C# compiler doesn't like a constructor with argument `Action` together with another constructor with argument `Action<object>` as the following error message tends to alert:

```
The call is ambiguous between the following methods or properties:
 'Grean.Exude.TestCase.TestCase(System.Action)' and
 'Grean.Exude.TestCase.TestCase(System.Action<object>)'
```

The _Exude_ project compiles but when I try to compile the _Exude.UnitTests_ project the build fails:

![image](https://f.cloud.github.com/assets/287532/2431385/236bf7f6-ad2c-11e3-8712-9721f79465b1.png)

**Comment by ploeh** [comment]
Oh, that's unexpected :( Out of curiosity: which line of code gives off that error?

**Comment by moodmosaic** [comment]
Great question! Thanks to it I just worked around the compiler error!

The error was at Line 37 of _TestCaseTests.cs_:
![image](https://f.cloud.github.com/assets/287532/2431635/d69585a0-ad3a-11e3-8fc5-7479e2fb07d1.png)

That's actually OK because there are now two overloads and null can actually refer to both. So, if I explicitly cast null to `Action<object>` it builds successfully:

![image](https://f.cloud.github.com/assets/287532/2431645/64361456-ad3b-11e3-9691-3264ac056c8d.png)

:+1:

**Comment by ploeh** [comment]
:+1:
